#
# Apache v2 license
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: "[Digital Signage] PR workflow"
run-name: "[Digital Signage] PR  workflow (by @${{ github.actor }} via ${{ github.event_name }})"
on:
  push:
    branches:
      - 'main'
    paths:
      - '**'
  pull_request:
    paths:
      - '**'
  workflow_call:
  workflow_dispatch:
  
permissions:
  contents: read
  packages: read
  pull-requests: read
  security-events: write
  actions: read

jobs:
  digital-signage-pre-merge-build:
    permissions:
      contents: read
      packages: read          # needed for actions/checkout
    runs-on: ubuntu-24.04
    steps:
    - name: Runner workspace path
      run: |
        echo "Cleaning up previous run"
        if [ -n "$(docker ps -aq)" ]; then
            docker stop $(docker ps -aq)
        fi
        if [ -n "$(docker ps -aq)" ]; then
            docker rm $(docker ps -aq)
        fi
        docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
          persist-credentials: false
    - name: Build
      run: |
        cd "${{ github.workspace }}"
        sed -i "s/DOCKER_REGISTRY=.*/DOCKER_REGISTRY=admin/g" .env
        make down
        # Generate random values for sensitive environment variables
        MTX_WEBRTCICESERVERS2_0_USERNAME=$(tr -dc 'a-zA-Z' < /dev/urandom | head -c 8)
        MTX_WEBRTCICESERVERS2_0_PASSWORD=$(openssl rand -hex 10)
        HOST_IP=$(hostname -I | awk '{print $1}')

        sed -i "s/MTX_WEBRTCICESERVERS2_0_USERNAME=.*/MTX_WEBRTCICESERVERS2_0_USERNAME=${MTX_WEBRTCICESERVERS2_0_USERNAME}/g" .env
        sed -i "s/MTX_WEBRTCICESERVERS2_0_PASSWORD=.*/MTX_WEBRTCICESERVERS2_0_PASSWORD=${MTX_WEBRTCICESERVERS2_0_PASSWORD}/g" .env
        sed -i "s/HOST_IP=.*/HOST_IP=${HOST_IP}/g" .env
        make build
    - name: Download models
      run: |
        cd "${{ github.workspace }}"
        echo "Downloading PID (YOLO11s) model"
        cd configs/pid && \
        wget https://raw.githubusercontent.com/intel-retail/automated-self-checkout/v3.6.3/download_models/downloadAndQuantizeModel.sh && \
        sed -i 's|MODELS_PATH="${MODELS_DIR:-/workspace/models}"|MODELS_PATH="${MODELS_DIR:-$PWD/models}"|g' downloadAndQuantizeModel.sh && \
        sed -i 's/MODEL_NAME="yolo11n"/MODEL_NAME="yolo11s"/g' downloadAndQuantizeModel.sh && \
        rm -rf .modelenv && \
        python3 -m venv .modelenv && \
        source .modelenv/bin/activate && \
        pip3 install -r model_download_requirements.txt && \
        rm -rf models && \
        chmod +x downloadAndQuantizeModel.sh && \
        ./downloadAndQuantizeModel.sh && \
        rm ./downloadAndQuantizeModel.sh && \
        deactivate && \
        cd ../..
        echo "Downloading AIG (SDXL-Turbo & MiniLM) models"
        cd aig && \
        rm -rf .modelenv && \
        python3 -m venv .modelenv && \
        source ./.modelenv/bin/activate && \
        pip3 install -r export-requirements.txt && \
        export HF_HUB_ENABLE_HF_TRANSFER=1 && \
        optimum-cli export openvino --model stabilityai/sdxl-turbo --task stable-diffusion-xl --weight-format int8 ./models/sdxl_turbo_ov/int8 && \
        huggingface-cli download sentence-transformers/all-MiniLM-L12-v2 --local-dir ./models/all-MiniLM-L12-v2 && \
        deactivate && \
        cd ../
    - name: Deploy
      run: |
        cd "${{ github.workspace }}"
        echo "Deploying digital-signage"
        make up
    - name: Undeploy
      if: always()
      run: |
        cd "${{ github.workspace }}"
        make down
  
  digital-signage-scans:
    uses: ./.github/workflows/scans.yaml
    with:
      target: all-scans